server:
  port: 8089
spring:
  application:
    name: lz-chat
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/lz-chat?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 设置最大文件大小
      max-request-size: 10MB  # 设置最大请求大小
feign:
  okhttp:
    enabled: true
Ipfs:
  api: /ip4/10.21.32.221/tcp/5001
jwt:
  key: key
rocketmq:
  name-server: 10.21.32.221:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: lzChat
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
