
spring:
  application:
    name: lz-file
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  #  profiles:
  #    active: dev
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 设置最大文件大小
      max-request-size: 10MB  # 设置最大请求大小
feign:
  okhttp:
    enabled: true
Ipfs:
  api: /ip4/10.21.32.221/tcp/5001
jwt:
  key: key
server:
  port: 8090
