server:
  port: 8080
spring:
  application:
    name: lz-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
    gateway:
      routes:
        - id: lz-user # 路由规则id，自定义，唯一
          uri: lb://lz-user # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
        - id: lz-auth
          uri: lb://lz-auth
          predicates:
            - Path=/login
            - Path=/register
  #    profiles:
  #      active: dev
  #  datasource:
  #    url: jdbc:mysql://10.21.32.154:3306/lz-user?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: root

  main:
    web-application-type: reactive

jwt:
  key: key

auth:
  exclude-paths: #无需登录校验的路径
    - /user/login
    - /user/register

#  redis:
#    address: redis://10.21.32.221:6379
#    password: 123456
#feign:
#  okhttp:
#    enabled: true