server:
  port:8080

spring:
  application:
    name: lz-user
  cloud:
    nacos:
      server-addr: 10.21.23.154:8848
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/lz-user?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    address: redis://10.21.32.221:6379
    password: 123456
feign:
  okhttp:
    enabled: true
