server:
  port: 8081

spring:
  application:
    name: lz-user
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  #  profiles:
  #    active: dev
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/lz-user?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 设置最大文件大小
      max-request-size: 10MB  # 设置最大请求大小
feign:
  okhttp:
    enabled: true
Ipfs:
  api: /ip4/10.21.32.221/tcp/5001
jwt:
  key: key

